CREATE TABLE IF NOT EXISTS POST (
    ID VARCHAR PRIMARY KEY,
    TIME TIMESTAMP,
    TEXT VARCHAR,
    KEYWORDS VARCHAR,
    FILTERS BOOLEAN,
    URL VARCHAR NOT NULL,
    LISTING_TITLE VARCHAR,
    LISTING_PRICE FLOAT,
    LISTING_LOCATION VARCHAR
);