CREATE TABLE IF NOT EXISTS POST (
    _ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION VARCHAR NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    KEYWORDS VARCHAR NOT NULL,
    URL VARCHAR NOT NULL,
);