name: Dockerfile Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: echo "DATABASE_URL=\"postgresql://postgres:postgres@localhost:5432/postgres\"" > .env
      - name: Build
        run: docker build -f docker/Dockerfile -t facebook-group-crawler .
      - name: Run
        run: docker run --network="host" -itd facebook-group-crawler